routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Controller@index');

// routers
Route::get('album-jobs/{id}', 'Controller@albumJobs')->name('album-jobs');
Route::get('jobs-images/{id}', 'Controller@jobImage')->name('jobs-images');

Route::resource('job', 'JobController');
Route::resource('image', 'ImageController');

Route::resource('album', 'AlbumController');

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    //
    public function albums()
    {
        return $this->belongsTo('App\Album');
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use Illuminate\Http\Request;

use App\Image;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data['objImages'] = Image::all();
        return view('image.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['method'] = 'POST';
        $data['action'] = route('image.store');
        $data['objAlbums'] = Album::all();

        return view('image.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $objImage = new Image();

        $path = '';
        if ($request->hasFile('image')) {
            $path = $request->image->store('images', 'public');
            $objImage->image = $path;
        }

        $objImage->message = $request->input('message');
        $objImage->display_message = $request->has('display_message') ? $request->input('display_message') : 0;
        $objImage->album_id = $request->input('album');

        $objImage->save();

        return redirect(route('image.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['objImage'] = Image::find($id);
        $data['objAlbums'] = Album::all();

        $data['method'] = 'PUT';
        $data['action'] = route('image.update', [$id]);

        return view('image.add', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $objImage = Image::fine($id);

        $path = '';
        if ($request->hasFile('image')) {
            $path = $request->image->store('images', 'public');
            $objImage->image = $path;
        }

        $objImage->message = $request->input('message');
        $objImage->display_message = $request->has('display_message') ? $request->input('display_message') : 0;
        $objImage->album_id = $request->input('album');

        $objImage->save();

        return redirect(route('image.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/image/add.blade.php
@extends('layouts.template')

@section('container')
<form action="{{$action}}" method="POST" enctype='multipart/form-data'>
    @csrf

    @method($method)

    <div class="form-group">
        <label for="image">Image</label>
        <input type="file" class="form-control" name="image">
    </div>

    <div class="form-group">
        <label for="message">Message</label>
        <input type="text" name="message" id="message" class="form-control" value="{{ isset($objImage->message) ? $objImage->message : ''}} " placeholder="enter message">
    </div>

    <div class="form-group">
        <label for="d-message">Disaplay message</label>
        <input type="checkbox" name="display_message" id="d-message" class="form-control" value="1">
    </div>

    <div class="form-group">
        <label for="album">Album</label>
        <select name="album" class="form-control">
            @forelse($objAlbums as $objAlbum)
            <option value={{$objAlbum->id}} {{isset($objImage) ? (($objAlbum->id == $objImage->album_id) ? 'selected' : '') : ''}}>{{$objAlbum->name}}</option>
            @empty
            <option>-- NONE-- </option>
            @endforelse
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>
@endsection

resources/views/image/list.blade.php
@extends('layouts.template')

@section('container')
<div class="content">
    <div class="row">
        <a href="{{route('image.create')}}">Add</a>
        <table class="table" id="data-table">
            <thead>
                <th>#</th>
                <th>Name</th>
                <th>Action</th>
            </thead>
            <tbody>
                @forelse($objImages as $objImage)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$objImage->image}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('image.edit',[$objImage->id])}}"><i class="fa fa-pencil"></i></a>
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="deleteRecord('{{route('image.destroy',[$objImage->id])}}', 'DELETE')"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                @empty
                Data Not Available
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection