routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Controller@index');

// routers
Route::get('album-jobs/{id}', 'Controller@albumJobs')->name('album-jobs');
Route::get('jobs-images/{id}', 'Controller@jobImage')->name('jobs-images');

Route::resource('job', 'JobController');
Route::resource('image', 'ImageController');

Route::resource('album', 'AlbumController');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    //
    public function albums()
    {
        return $this->belongsTo('App\Album');
    }

    public function images()
    {
        //return $this->hasManyThrough('App\Album', 'App\Image');
        return $this->morphOne('App\Image', 'imageable');
        //return $this->hasOneThrough('App\Image', 'App\Album');
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Job;
use App\Album;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['objJobs'] = Job::all();

        return view('job.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $data['action'] = route('job.store');
        $data['method'] = 'POST';
        $data['objAlbums'] = Album::all();

        return view('job.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $objJob = new Job;

        $objJob->name = $request->input('name');
        $objJob->album_id = $request->input('album');

        $objJob->save();

        return redirect(route('job.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['action'] = route('job.update', [$id]);
        $data['method'] = 'PUT';
        $data['objAlbums'] = Album::all();
        $data['objJob'] = Job::find($id);

        return view('job.add', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $objJob = Job::find($id);

        $objJob->name = $request->input('name');
        $objJob->album_id = $request->input('album');

        $objJob->save();

        return redirect(route('job.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Job::destroy($id);
    }
}

resources/views/job/add.blade.php
@extends('layouts.template')

@section('container')
<form action="{{$action}}" method="POST">

    @method($method)
    @csrf

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" value="{{ isset($objJob->name) ? $objJob->name : ''}} " placeholder="enter name">
    </div>

    <div class="form-group">
        <label for="album">Album</label>
        <select name="album" class="form-control">
            @forelse($objAlbums as $objAlbum)
            <option value={{$objAlbum->id}} {{isset($objJob) ? (($objAlbum->id == $objJob->album_id) ? 'selected' : '') : ''}}>{{$objAlbum->name}}</option>
            @empty
            <option>-- NONE-- </option>
            @endforelse
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>
@endsection

resources/views/job/list.blade.php
@extends('layouts.template')

@section('container')
<div class="content">
    <div class="row">
        <a href="{{route('job.create')}}">Add</a>
        <table class="table" id="data-table">
            <thead>
                <th>#</th>
                <th>Name</th>
                <th>Action</th>
            </thead>
            <tbody>
                @forelse($objJobs as $objJob)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$objJob->name}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('job.edit',[$objJob->id])}}"><i class="fa fa-pencil"></i></a>
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="deleteRecord('{{route('job.destroy',[$objJob->id])}}', 'DELETE')"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                @empty
                Data Not Available
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection