routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Controller@index');

// routers
Route::get('album-jobs/{id}', 'Controller@albumJobs')->name('album-jobs');
Route::get('jobs-images/{id}', 'Controller@jobImage')->name('jobs-images');

Route::resource('job', 'JobController');
Route::resource('image', 'ImageController');

Route::resource('album', 'AlbumController');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    //
    public function jobs()
    {
        return $this->hasMany('App\Job');
    }

    public function images()
    {
        return $this->hasMany('App\Image');
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Album;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data['objAlbums'] = Album::all();
        return view('album.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['method'] = 'POST';
        $data['action'] = route('album.store');

        return view('album.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $objAlbum = new Album();

        $objAlbum->name = $request->input('name');

        $objAlbum->save();

        return redirect(route('album.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['objAlbum'] = Album::find($id);

        $data['method'] = 'PUT';
        $data['action'] = route('album.update', [$id]);

        return view('album.add', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $objAlbum = Album::find($id);

        $objAlbum->name = $request->input('name');

        $objAlbum->save();

        return redirect(route('album.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Album::destroy($id);
    }
}

resources/views/album/add.blade.php
@extends('layouts.template')

@section('container')
<form action="{{$action}}" method="POST">
    @csrf

    @method($method)

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" value="{{ isset($objAlbum->name) ? $objAlbum->name : ''}} " placeholder="enter name">
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>
@endsection

resources/views/album/list.blade.php
@extends('layouts.template')

@section('container')
<div class="content">
    <div class="row">
        <a href="{{route('album.create')}}">Add</a>
        <table class="table" id="data-table">
            <thead>
                <th>#</th>
                <th>Name</th>
                <th>Action</th>
            </thead>
            <tbody>
                @forelse($objAlbums as $objAlbum)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$objAlbum->name}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('album.edit',[$objAlbum->id])}}"><i class="fa fa-pencil"></i></a>
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="deleteRecord('{{route('album.destroy',[$objAlbum->id])}}', 'DELETE')"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                @empty
                Data Not Available
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection